# Generated by Django 5.0.2 on 2024-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='thumbnil',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
